AWSTemplateFormatVersion: "2010-09-09"
Description: "Here are some details about the template."
Resources:
  myinstance-sri:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-0360c520857e3138f
      KeyName: mycft
      InstanceType: t3.micro
      Tags: 
        - Key: myec2
          Value: dev