AWSTemplateFormatVersion: '2010-09-09'
Description: 'AWS CloudFormation Template to create a single EC2 instance.'
Resources:
  MyEC2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      InstanceType: t3.micro
      ImageId: ami-05d2d839d4f73aafb
      Tags:
        - Key: Name
          Value: MySampleInstance
